### ISSUE TITLE
System.Reflection.TargetInvocationException when calling "RimuTec.Faker.Address.StreetAddress()" with Config.Locale = "ru"

### ISSUE THREAD

**Issue by trdsolutions** [RimuTec/Faker#2]
**Describe the bug**
`RimuTec.Faker.Address.StreetAddress()` throws an exception when the Locale is set to "ru".

**To Reproduce**
1. Create a project that targets .NET Framework 4.6.2 or use the test case with name "StreetAddress_With_Default_Values()"
2. Reference RimuTec.Faker (via dll / nuget)
3. Set locale to russian (`Config.Locale = "ru";`)
4. Call `RimuTec.Faker.Address.StreetAddress();`

**Expected behavior**
A street address would be returned, but an exception is thrown.

**Additional context**
I made the following changes to get it working at the GeneratorBase.cs file:

Line 83
Changed from
`return Fetch(fakerNode[locatorParts[0]], locatorParts.Skip(1).ToArray());`
To
`return Fetch(fakerNode[locatorParts[0].ToLowerInvariant()], locatorParts.Skip(1).ToArray());`

Line 98
Changed from
`return Fetch(fakerNode[locatorParts[0]], locatorParts.Skip(1).ToArray());`
To
`return Fetch(fakerNode[locatorParts[0].ToLowerInvariant()], locatorParts.Skip(1).ToArray());`

**Comment by ManfredLange** [comment]
@trdsolutions Thank you for reporting this issue. I am able to reproduce it.

**Comment by ManfredLange** [comment]
I now have a fix for this problem which will be included in the next release.

**Comment by ManfredLange** [comment]
This issue has been resolved in version 1.6.0 available at https://www.nuget.org/packages/RimuTec.Faker/

**Comment by trdsolutions** [comment]
I can confirm, that the issue was fixed 👍 :-)
