### ISSUE TITLE
RimuTec.Faker.Name.LastName() throws an YamlDotNet.Core.YamlException when locale is set to "pl"

### ISSUE THREAD

**Issue by trdsolutions** [RimuTec/Faker#3]
**Describe the bug**
Using `RimuTec.Faker.Name.LastName()` with locale "pl" throws an exception with the following message:

"_(Line: 48, Col: 5, Idx: 29115) - (Line: 48, Col: 9, Idx: 29119): Duplicate key_"

**To Reproduce**
1. Create a project that targets .NET Framework 4.6.2 or use the test case with name ""
2. Set `Config.Locale = "pl";`
3. Call `RimuTec.Faker.Name.LastName();`

**Expected behavior**
A last name will be generated instead of the thrown exception.

**Additional context**

**Comment by ManfredLange** [comment]
Thank you for submitting this great but report. I can reproduce this, too.

**Comment by ManfredLange** [comment]
I have a fix for this and am working towards a new release that will include the fix.

**Comment by ManfredLange** [comment]
This issue has been resolved in version 1.6.0 available at https://www.nuget.org/packages/RimuTec.Faker/

I'll keep the issue open for about a week. I'll close it then unless I hear that it has not been resolved.

**Comment by trdsolutions** [comment]
Thanks for the quick fix. I just wanted to say, that I cannot wait to get my hands on, but it's a little bit hard to find the time right now. But as soon as I tried it, I will let you know.
(And I have full trust, that this is fixed ;-) )

**Comment by trdsolutions** [comment]
I can confirm, that the issue was fixed, thank you 👍 :-)
